### PR TITLE
Migrated to Qt 6 with PySide6 to able run under arm macs

### PR DESCRIPTION
**Pull request by akhoruzhenko**

### CODE REVIEW

**Comment by gifuhabu** [comment]
thanks for updating to PyQt6!
I have built and tried the app on mac and windows but it cannot both seem to get the audio to play.
Is this problem happening in your environment?

**Comment by akhoruzhenko** [comment]
Yes, this is known issue. I'm going to work with it this week.

**Comment by akhoruzhenko** [comment]
@gifuhabu try updated version, I fix bug with context menu in the page and now it can play audio

**Comment by gifuhabu** [comment]
@akhoruzhenko 
Thanks for fixing audio to play quickly.
Now button to play works, but reloading word page by switching page or monitoring clipboard, it doesn't seem audio to play. (previous official build works)
Do you have any idea to fix this?

**Comment by akhoruzhenko** [comment]
@gifuhabu fixed, you can check auto pronunciation now

**Comment by gifuhabu** [comment]
Thanks for fixing that! It works like charm.
I found a bug that if you immediately switch to a page of words, the screen freezes and an exception occurs.

For example
```
Traceback (most recent call last):
  File "ldoce5viewer\qtgui\main.py", line 698, in _onClipboardChanged
AttributeError: 'MainWindow' object has no attribute 'isActiveWindow'. Did you mean: 'activateWindow'?
Traceback (most recent call last):
  File "ldoce5viewer\qtgui\main.py", line 698, in _onClipboardChanged
AttributeError: Slot 'MainWindow::_onUrlChanged(QUrl)' not found.
```

You can see that this occurs when you drag and drop against the word list in the sidebar.
The official build works fine.

**Comment by JBraddockm** [comment]
Thank you for the update. Is there a way you can share the final app as I am unable to build it from the source?

**Pull request merged**
